--- # Jekyll's config
name: Resume℠
email: michelc@resumesm.gq
title: Resume℠ 
summary: Resume Service Mark

netname: happy-heisenberg-d5da00
url: https://happy-heisenberg-d5da00.netlify.com

pgw: https://cloudflare-ipfs.com
icdn: https://cdn.statically.io/img/gateway.ipfs.io

search_url: https://duckduckgo.com/?q

sass_dir: _sass
